builds:
  - id: "torproxy"
    main: ./cmd
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    binary: torproxy
checksum:
  name_template: "checksums.txt"
signs:
  - artifacts: checksum
    args:
      [
        "--batch",
        "-u",
        "{{ .Env.GPG_FINGERPRINT }}",
        "--output",
        "${signature}",
        "--detach-sign",
        "${artifact}",
      ]
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  use: github-native
archives:
  - id: torproxy
    format: binary
    builds:
      - torproxy
    name_template: "torproxy-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
dockers:
  - dockerfile: Dockerfile
    # image templates
    image_templates:
      - "ghcr.io/tdex-network/torproxy:{{ .Tag }}"
      - "ghcr.io/tdex-network/torproxy:latest"
    # GOOS of the built binaries/packages that should be used.
    goos: linux
    # GOARCH of the built binaries/packages that should be used.
    goarch: amd64
    # Template of the docker build flags.
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    extra_files:
      - go.mod
      - go.sum
      - cmd
      - pkg
