version: "3.7"
services:
  proxy:
    ports:
      - "443:443"
      - "80:80"
    container_name: proxy
    restart: unless-stopped
    image: ghcr.io/tdex-network/torproxy
    entrypoint: torproxy start
    command:
      - --domain=${DOMAIN}
      - --email=${EMAIL}
      - --registry=${REGISTRY}
      - --use-tor
